import type { HclValue } from "../hcl";
import { safeName } from "../hcl";
import type { GeneratedFile, ProviderDefinition, VariableSpec } from "../types";
import type { GenerationResult as TerraformGenerationResult } from "../terraform/generate";

export type PulumiGenerationResult = {
  files: GeneratedFile[];
  resourceCount: number;
  unresolved: TerraformGenerationResult["unresolved"];
  deploymentCommand: string;
};

const tsString = (value: string) => JSON.stringify(value);

function pulumiProjectName(projectName: string) {
  const normalized = safeName(projectName || "infracanvas", "infracanvas").replace(/_/g, "-");
  return normalized.slice(0, 100) || "infracanvas";
}

function hclDefaultToTypeScript(value: HclValue): string | undefined {
  switch (value.kind) {
    case "string":
    case "heredoc":
      return tsString(value.value);
    case "number":
    case "bool":
      return String(value.value);
    case "list": {
      const items = value.items.map(hclDefaultToTypeScript);
      return items.some((item) => item === undefined) ? undefined : `[${items.join(", ")}]`;
    }
    case "object": {
      const entries = value.entries.map(([key, entry]) => [key, hclDefaultToTypeScript(entry)] as const);
      if (entries.some(([, entry]) => entry === undefined)) return undefined;
      return `{ ${entries.map(([key, entry]) => `${tsString(key)}: ${entry}`).join(", ")} }`;
    }
    case "raw":
      return value.value === "null" ? "undefined" : undefined;
  }
}

function configExpression(spec: VariableSpec) {
  const isList = spec.type.startsWith("list") || spec.type.startsWith("set") || spec.type.startsWith("tuple");
  const isObject = spec.type.startsWith("map") || spec.type.startsWith("object");
  const isNumber = spec.type === "number";
  const isBool = spec.type === "bool" || spec.type === "boolean";
  const typeArgument = isList ? "unknown[]" : isObject ? "Record<string, unknown>" : "unknown";
  const getter = spec.sensitive
    ? "getSecret"
    : isList || isObject
      ? `getObject<${typeArgument}>`
      : isNumber
        ? "getNumber"
        : isBool
          ? "getBoolean"
          : "get";
  const requiredGetter = spec.sensitive
    ? "requireSecret"
    : isList || isObject
      ? `requireObject<${typeArgument}>`
      : isNumber
        ? "requireNumber"
        : isBool
          ? "requireBoolean"
          : "require";

  if (spec.default === undefined) return `config.${requiredGetter}(${tsString(spec.name)})`;
  const fallback = hclDefaultToTypeScript(spec.default);
  if (fallback === undefined) return `config.${getter}(${tsString(spec.name)})`;
  if (spec.sensitive) {
    return `config.${getter}(${tsString(spec.name)}) ?? pulumi.secret(${fallback})`;
  }
  return `config.${getter}(${tsString(spec.name)}) ?? ${fallback}`;
}

function indexFile(terraform: TerraformGenerationResult, projectName: string) {
  const args = [...terraform.variables]
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((spec) => `  ${spec.name}: ${configExpression(spec)},`)
    .join("\n");
  const exports = terraform.outputs.length
    ? terraform.outputs
        .map(
          (output) =>
            `export const ${safeName(output.name)} = infrastructure.${safeName(output.name)};`,
        )
        .join("\n")
    : "export const deploymentUrn = infrastructure.urn;";

  return `import * as pulumi from "@pulumi/pulumi";
import * as infracanvas from "@pulumi/infracanvas";

// This strongly typed local package is generated by the Pulumi CLI from the
// complete Terraform module in ./terraform. Pulumi owns stack state and the
// deployment lifecycle; the module preserves every InfraCanvas graph reference.
const config = new pulumi.Config();

const infrastructure = new infracanvas.Module(${tsString(
    pulumiProjectName(projectName),
  )}, {
${args}
});

${exports}
`;
}

function pulumiYaml(projectName: string, provider: ProviderDefinition) {
  return `name: ${pulumiProjectName(projectName)}
runtime:
  name: nodejs
  options:
    packagemanager: npm
description: InfraCanvas ${provider.shortName} architecture deployed and managed by Pulumi
`;
}

function packageJson(projectName: string) {
  return `${JSON.stringify(
    {
      name: `${pulumiProjectName(projectName)}-pulumi`,
      version: "1.0.0",
      private: true,
      scripts: {
        bootstrap: "node scripts/pulumi.mjs bootstrap",
        preview: "node scripts/pulumi.mjs preview",
        deploy: "node scripts/pulumi.mjs up",
        destroy: "node scripts/pulumi.mjs destroy",
        typecheck: "tsc --noEmit",
      },
      dependencies: {
        "@pulumi/pulumi": "^3.0.0",
      },
      devDependencies: {
        "@types/node": "^22.0.0",
        typescript: "^5.9.0",
      },
    },
    null,
    2,
  )}\n`;
}

const TSCONFIG = `{
  "compilerOptions": {
    "strict": true,
    "target": "ES2022",
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "outDir": "dist"
  },
  "include": ["index.ts"]
}
`;

function deploymentScript(requiredVariables: VariableSpec[]) {
  const required = requiredVariables
    .filter((variable) => variable.default === undefined)
    .map((variable) => ({ name: variable.name, secret: Boolean(variable.sensitive) }));

  return `import { spawnSync } from "node:child_process";

const action = process.argv[2] ?? "preview";
const stack = process.env.PULUMI_STACK ?? "dev";
const required = ${JSON.stringify(required, null, 2)};

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: process.cwd(),
    encoding: "utf8",
    shell: process.platform === "win32",
    stdio: options.capture ? "pipe" : "inherit",
  });
  if (result.error) {
    console.error(\`Unable to run \${command}: \${result.error.message}\`);
    process.exit(1);
  }
  if (options.capture) return result;
  if (result.status !== 0) process.exit(result.status ?? 1);
  return result;
}

function hasCommand(command) {
  const result = run(command, ["version"], { capture: true });
  return result.status === 0;
}

if (!hasCommand("pulumi")) {
  console.error("Pulumi CLI is required: https://www.pulumi.com/docs/iac/download-install/");
  process.exit(1);
}

console.log("\\nInfraCanvas: generating the local Pulumi SDK from ./terraform...");
run("pulumi", ["package", "add", "terraform-module", "./terraform", "infracanvas"]);

console.log("\\nInfraCanvas: installing the generated SDK and TypeScript dependencies...");
run(process.platform === "win32" ? "npm.cmd" : "npm", ["install"]);

const selected = run("pulumi", ["stack", "select", stack], { capture: true });
if (selected.status !== 0) run("pulumi", ["stack", "init", stack]);

const missing = required.filter(({ name }) => {
  const current = run("pulumi", ["config", "get", name, "--stack", stack], { capture: true });
  return current.status !== 0 || !current.stdout.trim();
});
if (missing.length > 0 && action !== "bootstrap") {
  console.error("\\nSet these required values before deployment:");
  for (const item of missing) {
    const secretFlag = item.secret ? " --secret" : "";
    console.error(\`  pulumi config set\${secretFlag} \${item.name} <value> --stack \${stack}\`);
  }
  process.exit(2);
}

if (action === "bootstrap") {
  console.log("\\nPulumi project is ready. Set required config, then run npm run preview.");
  process.exit(0);
}
if (!["preview", "up", "destroy"].includes(action)) {
  console.error(\`Unsupported action: \${action}\`);
  process.exit(2);
}

run("pulumi", [action, "--stack", stack]);
`;
}

function configExample(projectName: string, variables: VariableSpec[]) {
  const project = pulumiProjectName(projectName);
  const lines = [
    `# Rename to Pulumi.dev.yaml only after replacing required placeholders.`,
    `# Prefer \"pulumi config set --secret <key> <value>\" for sensitive values.`,
    "config:",
  ];
  [...variables]
    .sort((a, b) => a.name.localeCompare(b.name))
    .forEach((variable) => {
      const defaultValue = variable.default ? hclDefaultToTypeScript(variable.default) : undefined;
      lines.push(`  # ${variable.description}`);
      if (variable.sensitive) {
        lines.push(`  # ${project}:${variable.name}: set-with-pulumi-config---secret`);
      } else if (variable.default === undefined) {
        lines.push(`  ${project}:${variable.name}: REPLACE_ME`);
      } else {
        lines.push(`  # ${project}:${variable.name}: ${defaultValue ?? "uses Terraform default"}`);
      }
    });
  return `${lines.join("\n")}\n`;
}

function readme(
  projectName: string,
  provider: ProviderDefinition,
  terraform: TerraformGenerationResult,
) {
  const required = terraform.variables.filter((variable) => variable.default === undefined);
  const configCommands = required
    .map(
      (variable) =>
        `pulumi config set${variable.sensitive ? " --secret" : ""} ${variable.name} <value>`,
    )
    .join("\n");
  const coverageNotice = terraform.diagramOnly.length
    ? `\n> **Generation boundary:** ${terraform.diagramOnly.length} official architecture ${terraform.diagramOnly.length === 1 ? "service is" : "services are"} retained in the diagram but intentionally omitted from deployment code until verified provider configuration is modeled.\n`
    : "";
  return `# ${projectName || "InfraCanvas Pulumi infrastructure"}

This is a complete **Pulumi TypeScript** project generated by InfraCanvas for
**${provider.name}**. It consumes the generated configuration in \`./terraform\`
through Pulumi's official local Terraform Module provider. Pulumi manages the
stack, state, previews, updates, and outputs while preserving all
${terraform.resourceCount} generated provider resources and diagram connections.
${coverageNotice}

## Prerequisites

- Node.js 20 or newer
- Pulumi CLI 3.153 or newer
- Credentials for ${provider.name}

## Deploy

\`\`\`bash
npm install
npm run bootstrap
${configCommands || "# No required configuration values for this diagram."}
npm run preview
npm run deploy
\`\`\`

On Windows you can also run \`./deploy.ps1\`; on macOS/Linux run
\`./deploy.sh\`. The deploy remains safety-gated: Pulumi shows the preview and
asks for confirmation before creating or changing infrastructure.

Set a different stack with \`PULUMI_STACK=staging\` (PowerShell:
\`$env:PULUMI_STACK='staging'\`). Never commit real stack configuration or
plaintext secrets.

## Why the Terraform folder exists

Pulumi officially supports local Terraform modules. During bootstrap,
\`pulumi package add terraform-module ./terraform infracanvas\` generates a
strongly typed local SDK imported by \`index.ts\`. OpenTofu is managed by the
Pulumi provider; separate Terraform state is not used.

Documentation: https://www.pulumi.com/docs/iac/guides/building-extending/using-existing-tools/use-terraform-module/
`;
}

const ROOT_GITIGNORE = `node_modules/
dist/
.pulumi/

# Stack files may contain deployment metadata. Create them locally.
Pulumi.*.yaml
!Pulumi.*.yaml.example

# Generated local SDK/package caches
sdks/
`;

const DEPLOY_PS1 = `$ErrorActionPreference = "Stop"
npm install
node scripts/pulumi.mjs up
`;

const DEPLOY_SH = `#!/usr/bin/env sh
set -eu
npm install
node scripts/pulumi.mjs up
`;

export function generatePulumi(
  provider: ProviderDefinition,
  terraform: TerraformGenerationResult,
  projectName: string,
): PulumiGenerationResult {
  const terraformFiles: GeneratedFile[] = terraform.files.map((file) => ({
    ...file,
    path: `terraform/${file.path}`,
  }));
  const files: GeneratedFile[] = [
    { path: "Pulumi.yaml", language: "yaml", contents: pulumiYaml(projectName, provider) },
    { path: "index.ts", language: "typescript", contents: indexFile(terraform, projectName) },
    { path: "package.json", language: "json", contents: packageJson(projectName) },
    { path: "tsconfig.json", language: "json", contents: TSCONFIG },
    {
      path: "Pulumi.dev.yaml.example",
      language: "yaml",
      contents: configExample(projectName, terraform.variables),
    },
    {
      path: "scripts/pulumi.mjs",
      language: "javascript",
      contents: deploymentScript(terraform.variables),
    },
    { path: "deploy.ps1", language: "powershell", contents: DEPLOY_PS1 },
    { path: "deploy.sh", language: "shell", contents: DEPLOY_SH },
    {
      path: "README.md",
      language: "markdown",
      contents: readme(projectName, provider, terraform),
    },
    { path: ".gitignore", language: "text", contents: ROOT_GITIGNORE },
    ...terraformFiles,
  ];
  return {
    files,
    resourceCount: terraform.resourceCount,
    unresolved: terraform.unresolved,
    deploymentCommand: "npm run deploy",
  };
}
